version: '3.9'

services:
  app:
    build: .
    container_name: nest_app
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
      MONGO_URI: ${MONGO_URI_DOCKER}
    ports:
      - '3333:3333'
    depends_on:
      - mysql
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
